name: pipeline
on: [push]

jobs: 
    test:
      runs-on: ubuntu-latest
      
      steps:
        - name: copiar repositorio
          uses: actions/checkout@v4

        - name: listar arquivos e diretórios
          run: ls -R

        - name: abrir codigo
          run: python calc.py